fix: build error: set window.setTimeout
* fix error TS2322: Type 'Timeout' is not assignable to type 'number'.
* caused by previous tsconfig changes when setting up support for tests?